name: Claude Blog Post Review

permissions:
  contents: read
  pull-requests: write
  issues: write

on:
  pull_request:
    types: [opened]  # Only on first open, not on synchronize (pushes)
    paths:
      - 'posts/**/*.md'
      - 'authors/*.json'
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

jobs:
  # Automatic review on PR open only
  auto-review:
    if: github.event_name == 'pull_request' && !github.event.pull_request.draft
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}  # Check out the PR branch, not main
          fetch-depth: 0  # Get full history for better context

      - name: Claude Blog Post Review
        uses: anthropics/claude-code-action@beta
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          direct_prompt: |
            Please perform a comprehensive review of this blog post focusing on:

            ## Critical Analysis Areas:

            1. **Content Quality**:
               - Technical accuracy of all claims and examples
               - Correctness of code snippets and mathematical formulas
               - Proper citations and attributions
               - No misleading or unsupported statements
               - Clear distinction between facts and speculation

            2. **Structure & Flow**:
               - Logical progression of ideas
               - Clear introduction that hooks the reader
               - Well-organized sections without repetition
               - Smooth transitions between topics
               - Strong conclusion that ties everything together
               - Appropriate use of headings (H2, H3, etc.)

            3. **Writing Quality**:
               - Grammar and spelling
               - Clear, concise sentences
               - Active voice where appropriate
               - Consistent tone and style
               - Avoiding jargon without explanation
               - Proper punctuation and formatting

            4. **Technical Examples**:
               - All code snippets are syntactically correct
               - Code examples follow best practices
               - Albumentations usage is correct and up-to-date
               - Image processing operations are properly explained
               - Mathematical notation uses LaTeX format:
                 * Inline math: $formula$ not `formula`
                 * Block math: $$formula$$ not ```math
                 * Proper LaTeX commands (\frac, \partial, \sum, \sqrt, etc.)
                 * Matrices use \begin{bmatrix}...\end{bmatrix}

            5. **Blog Post Standards**:
               - Proper YAML frontmatter (title, date, author, tags, categories, excerpt)
               - Meaningful excerpt that summarizes the post
               - Appropriate tags and categories
               - Images have alt text for accessibility
               - Links are working and relevant
               - Code blocks have proper language highlighting

            6. **SEO & Readability**:
               - Compelling title that includes key terms
               - Clear value proposition in the introduction
               - Good use of subheadings for scannability
               - Appropriate post length (not too short or too long)
               - Key concepts are explained clearly

            7. **Engagement**:
               - Interesting examples and use cases
               - Visual aids where helpful (code, diagrams, images)
               - Practical takeaways for readers
               - Appropriate depth indicators if used
               - Clear target audience

            ## Review Format:

            Start with a brief summary of the post's strengths and areas for improvement, then provide specific feedback organized by severity:
            
            - 🔴 **Critical**: Must fix before publishing (factual errors, broken code, misleading information)
            - 🟡 **Important**: Should fix (clarity issues, structure problems, missing context)
            - 🟢 **Suggestion**: Nice to have (style improvements, additional examples, minor enhancements)

            For each issue, provide:
            1. Section and line number (if applicable)
            2. Current text/code
            3. Suggested improvement
            4. Explanation of why this matters

            Also highlight what was done particularly well in the post.

            If this is a technical deep-dive (like the normalization post), verify:
            - Mathematical rigor where claims are made
            - Clear distinction between proven facts and empirical observations
            - Appropriate citations for academic claims
            - Code examples that readers can actually run
            - LaTeX math is compatible with Next.js MDX rendering (remark-math + rehype-katex)
            - All mathematical variables use proper LaTeX notation ($x_i$ not `xᵢ`)

  # Manual review trigger via @claude comment
  manual-review:
    if: |
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude'))
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}  # Check out the latest commit
          fetch-depth: 0

      - name: Claude Manual Blog Review
        uses: anthropics/claude-code-action@beta
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}